# LetsUpgrade Data Science Essentials FEB 2021 | Batch 1 - Assignment

## Nikhil R

https://community.letsupgrade.in/post/data-science-essentials-feb-2021-batch-1-day-5-overview-6038bec07fadee0cd6456165

## Question 1:
Given the following jumbled word, OBANWRI guess the correct English word.

* A. RANIBOW
* B. RAINBOW
* C. BOWRANI
* D. ROBWANI

**Answer : B. RAINBOW**



##Question 2:
Write a program that prints “LETS UPGRADE”. (Please note that you have to print in ALL CAPS
as given)

In [2]:
print("LETS UPGRADE")

LETS UPGRADE


# Question 3:
Write a program that takes cost price and selling price as input and
displays whether the transaction is a Profit or a Loss or Neither.

INPUT FORMAT
* The first line contains the cost price.
* The second line contains the selling price.

OUTPUT FORMAT
* Print "Profit" if the transaction is a profit or "Loss" if it is a loss. If it is neither
* profit nor loss, print "Neither". (You must not have quotes in your output)


NOTE:
Please stick to the input and output format. Don't add anything extra like
'Enter cost price', 'Enter selling price', etc.

In [3]:
cp=int(input())
sp=int(input())
if cp==sp:
  print("Neither")
elif cp>sp:
  print("Loss")
else:
  print("Profit")

70
90
Profit


# Question 4:
Write a program that takes an amount in Euros as input. You need to find its equivalent in
Rupees and display it. Assume 1 Euro equals Rs. 80.

Please note that you are expected to stick to the given input and output
format as in sample test cases. Please don't add any extra lines such as
'Enter a number’ etc.
Your program should take only one number as input and display the output.

In [4]:
print(int(input())*80)

50
4000


# Question 5:
Create an empty list. Accept 10 numbers from the user and append to it the list if it is an even
number.

In [5]:
l=[]
for i in range(10):
  a=int(input())
  if a%2==0:
    l.append(a)
print(l)  

10
1
3
12
1205
4663
023
458
1
23
[10, 12, 458]


# Question 6:
Create a notebook on LIST COMPREHENSION. This exercise is to put you in a
Self-learning mode

In [6]:
#Example program
n=int(input())
a=[i*i for i in range(n)]
print(a)

78
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929]


# Question 7:

In this assignment, given a number n, you have to write a program that generates a dictionary d which contains (i, i*i), where i is from 1 to n (both included).
Then you have to just print this dictionary d.

Example:

Input: 4 will give output as {1: 1, 2: 4, 3: 9, 4: 16}

Input Format: Take the number n in a single line.
Output Format: Print the dictionary d in a single line.

In [7]:
n=int(input())
d=dict()
for i in range(1,n+1):
  d[i]=i*i
print(d)

9
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


# Questions 8:
There is a robot that wants to go to the charging point to charge itself.
The robot moves in a 2-D plane from the original point (0,0). The robot can
move toward UP, DOWN, LEFT, and RIGHT with given steps.

The trace of robot movement is shown as the following:

UP 5

DOWN 3

LEFT 3

RIGHT 2

Then, the output of the program should be: 2

The numbers after the direction are steps.

Write a program to compute the distance between the current position after
a sequence of movement and the original point. 
If the distance is float, then
just print the nearest integer (use round() function for that and then convert
it into an integer).

Input Format:

The first line of the input contains a number n which implies the number of
directions to be given.
The next n lines contain the direction and the step separated by a space.

Output Format:

Print the distance from the original position to the current position.

Example:

Input: 
4

UP 5

DOWN 3

LEFT 3

RIGHT 2

Output: 2

In [13]:
import math
from math import sqrt
n=int(input("Enter the no of directions"))
start=[0,0]
end=[0,0]
for i in range(n):
  direction,step=map(str,input().split())
  step=int(step)
  if direction == "UP":
    start[0]-=step
  elif direction == "DOWN":
    start[0]+=step
  if direction == "LEFT":
    start[1]-=step
  if direction == "RIGHT":
    start[1]+=step

d = math.sqrt((end[0]-start[0])**2 + (end[1]-start[1])**2)

print(int(d))

Enter the no of directions4
UP 5
DOWN 3
LEFT 3
RIGHT 2
2


## IMPORTING NUMPY

In [14]:
import numpy as np


## Questions 9:
Create a NumPy array starting from 2 till 50 with a step size of 3.

In [17]:
a=np.arange(2,51,3)
print(a)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


#Questions 10:
Accept two lists of 5 elements each from the user.
Convert them to NumPy arrays. Concatenate these arrays and print them. Also, sort these arrays
and print them.

In [20]:
a=list(map(int,input().split()))
b=list(map(int,input().split()))
p=np.array(a)
q=np.array(b)
c=p+q
print(c)
c.sort()
print("After sorting : ")
print(c)

1 2 3 4 5
11 89 34 87 99
[ 12  91  37  91 104]
After sorting : 
[ 12  37  91  91 104]


##Questions 11:
Write a code snippet to find the dimensions of a ndarray and its size.


In [26]:
a=[ [10,11,12],[13,14,15],[16,17,18] ]
ap=np.array(a)
print("Dimension of \n{} is {}".format(ap,np.ndim(ap)))
print("Size of \n{} is {}".format(ap,np.size(ap)))

Dimension of 
[[10 11 12]
 [13 14 15]
 [16 17 18]] is 2
Size of 
[[10 11 12]
 [13 14 15]
 [16 17 18]] is 9


##Questions 12:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [46]:
d1=np.arange(10)
#using reshape method
d2=d1.reshape(5,2)
print(d2)
#using newaxis method 
#https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis
d3 = d1[:, np.newaxis]
print(d3)
#using y = np.expand_dims(x, axis=0)
#https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html
y= np.expand_dims(d1,axis=(1,0))
print(y)



[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[[0 1 2 3 4 5 6 7 8 9]]]


##Questions 13:
Consider two square NumPy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [50]:
p=np.arange(25).reshape(5,5)
q=np.arange(25,50).reshape(5,5)
print(p)
print(q)

stacked_vertical = np.vstack((p,q))
print(stacked_vertical)
stacked_horizontal = np.hstack((p,q))
print(stacked_horizontal)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0  1  2  3  4 25 26 27 28 29]
 [ 5  6  7  8  9 30 31 32 33 34]
 [10 11 12 13 14 35 36 37 38 39]
 [15 16 17 18 19 40 41 42 43 44]
 [20 21 22 23 24 45 46 47 48 49]]


##Questions 14:
How to get unique items and counts of unique items?

In [65]:
print("Just normal python \n")
a=list(range(10))
a+=[1,1,14,5,56,77,7,7,9,9,6,6,3]
print("original list \n\t",a)
u=set(a)
print(" Unique Values \n\t{} \n Count of Unique Values is {} \n\n".format(u,len(u)))

print("Using Numpy \n")
#https://numpy.org/doc/stable/reference/generated/numpy.unique.html
#https://thispointer.com/python-find-unique-values-in-a-numpy-array-with-frequency-indices-numpy-unique/
q=np.array(a)
print("Original Numpy Array is \n\t",q)
k=np.unique(q)
print(" Unique Values \n\t{} \n Count of Unique Values is {} \n\n".format(k,len(k)))

Just normal python 

original list 
	 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 14, 5, 56, 77, 7, 7, 9, 9, 6, 6, 3]
 Unique Values 
	{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 77, 14, 56} 
 Count of Unique Values is 13 


Using Numpy 

Original Numpy Array is 
	 [ 0  1  2  3  4  5  6  7  8  9  1  1 14  5 56 77  7  7  9  9  6  6  3]
 Unique Values 
	[ 0  1  2  3  4  5  6  7  8  9 14 56 77] 
 Count of Unique Values is 13 


